### ISSUE TITLE
ReferenceError: window is not  defined

### ISSUE THREAD

**Issue by lsaether** [parity-js/api#6]
```
(node:22916) UnhandledPromiseRejectionWarning: ReferenceError: window is not
 defined
    at Object.<anonymous> (/home/logan/.nvm/versions/node/v9.3.0/lib/node_modul
es/eac.js/node_modules/@parity/api/lib/provider/ipc.js:20:19)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/logan/.nvm/versions/node/v9.3.0/lib/node_modul
es/eac.js/node_modules/@parity/api/lib/provider/index.js:18:11)
    at Module._compile (module.js:660:30)
```

The code using Parity API package:
```
const hasPendingParity = async (conf, txRequest) => {
	/// Only available if using parity locally.
	const pApi = require("@parity/api")
	const provider = new pApi.Provider.Http(`${conf.provider}`)
	const api = new pApi(provider)

	const transactions = await api.parity.pendingTransactions()
	const recips = transactions.map(tx => tx.to)
	if (recips.indexOf(txRequest.address) !== -1) return true
	return false
}
```

As far as I can tell this has to do with the IPC provider which was added in the latest release. I'm going to downgrade since this was last working on version 2.1.16.

**Comment by jacogr** [comment]
Fixed in 2.1.20
